### ISSUE TITLE
The url of dataset is invalid

### ISSUE THREAD

**Issue by ErinChen1** [LiheYoung/SenseEarth2020-ChangeDetection#1]
The url of dataset is invalid~~~~~

**Comment by LiheYoung** [comment]
Hi @ErinChen1,

I checked it. It is valid, would you mind trying it again?

**Comment by ErinChen1** [comment]
> Hi @ErinChen1,
> 
> I checked it. It is valid, would you mind trying it again?

![IMG_7706](https://user-images.githubusercontent.com/26476348/104910647-96005b80-59c4-11eb-98b3-bb863dd5aed6.JPG)

hmmmmmmm
