### ISSUE TITLE
BatchSize问题

### ISSUE THREAD

**Issue by wanghao15536870732** [LiheYoung/SenseEarth2020-ChangeDetection#10]
非常抱歉，再一次冒昧打扰。有个问题想请教一下，当我以resnet101为backbone，deeplabv3plus为model，batch size设为2进行训练时，会出现batchnormalization只有一个sample的情况。为了找寻原因，打印了网络输入的tensor大小，发现虽然网络输入img1和img2的shape为[2, 3, 512, 512]，但在BaseNet的forward中却输出了四张[1, 3, 512, 512]大小的张量，这也是导致batch size设置为2时会报错的原因，我很不理解，想问下其中的原因，谢谢了。
```python
# deeplabv3plus.py
for i, (img1, img2, mask1, mask2, mask_bin) in enumerate(tbar):
    img1, img2 = img1.cuda(), img2.cuda()
    mask1, mask2 = mask1.cuda(), mask2.cuda()
    mask_bin = mask_bin.cuda()
    print(img1.shape) # [2, 3, 512, 512]
    print(img2.shape) # [2, 3, 512, 512]
```

```python
# base.py
def forward(self, x1, x2, tta=False):
    print(x1.shape)  # 打印出四张shape为[1, 3, 512, 512]的Tensor
    print(x2.shape)
```

**Comment by LiheYoung** [comment]
你好，

是否因为用了2块GPU呢，BatchSize平均到每块GPU上就只有1，所以导致了BatchNorm的报错。

**Comment by wanghao15536870732** [comment]
嗯嗯，我刚刚尝试单卡，是这样的，非常感谢。
