### ISSUE TITLE
关于标签的问题

### ISSUE THREAD

**Issue by albert28wen** [LiheYoung/SenseEarth2020-ChangeDetection#15]
楼主你好，在阅读楼主的源代码的时候，有些地方不是很明白，希望能得到楼主的指点：
1、在change_detection.py中
    CLASSES = ['未变化区域', '水体', '地面', '低矮植被', '树木', '建筑物', '运动场'] 
    以及商汤提供的标签都指明 未变化区域标记为0，水体标记为1，地面为2，低矮植被为3，树木为4，建筑物为5，运动场为6。
   但是，在随后的一段代码中：
            if self.mode == 'train':
                gt_mask1 = np.array(Image.open(os.path.join(self.root, 'label1', id)))
                mask_bin = np.zeros_like(gt_mask1)
                mask_bin[gt_mask1 == 0] = 1
                mask_bin = Image.fromarray(mask_bin)
  为什么把mask_bin 标签为0都改为1？标签为0不是表示改区域未发生变化吗？

2、在训练代码train.py中：
                out1, out2, out_bin = self.model(img1, img2)

                loss1 = self.criterion(out1, mask1 - 1)
                loss2 = self.criterion(out2, mask2 - 1)
      计算损失的时候，为什么mask1和mask2需要减1呢？

**Comment by LiheYoung** [comment]
1. 我们代码中使用了0表示变化，1表示未变化，在测试时的时候也进行了相应的反转。当然也可以依照原数据集，不进行反转。
2. 因为输出的out1和out2的index是从0开始的，而标签mask1和mask2的index是从1开始的，需要调整一致。

**Comment by albert28wen** [comment]
对于问题2，还是有一点不是很明白，在CLASSES = ['未变化区域', '水体', '地面', '低矮植被', '树木', '建筑物', '运动场']中

out1和out2应该是单纯的语义分割，未变化区域应该也是作为一类(背景？)进行训练的，他的index是0；
给官方提供的数据标签label1和label2着色进行观察，index应该是0开始的

**Comment by LiheYoung** [comment]
在语义分割任务中只含有['水体', '地面', '低矮植被', '树木', '建筑物', '运动场']这几个类别，没有“背景”或“未变化区域”类别，因为“未变化区域”这个类别通过单张图像是无法确定的，而我们的语义分割任务是针对单张输入图像进行的分割。

**Comment by albert28wen** [comment]
可是我下载的官方数据提供的label1 和label2 的数值确实是从0到6的，不是1到6，难道是我下载的数据标签不是官方原始的？

**Comment by LiheYoung** [comment]
数据集中的0是表示未变化区域，在语义分割中是用不到这个类别的。在语义分割中用0-5表示原数据集中的1-6，所以需要减1。

**Comment by shanhuhaifeng** [comment]
请问一下，val集的标签是否可以提供一下呢？

**Comment by LiheYoung** [comment]
抱歉，比赛中只提供了训练集的标签。
