### ISSUE TITLE
Cannot access Datasets

### ISSUE THREAD

**Issue by Saddam1235** [LiheYoung/SenseEarth2020-ChangeDetection#16]
Hello Sir,
unfortunately i cannot have access to datasets. can you please provide any suitable ink to download dataset.

**Comment by LiheYoung** [comment]
Hi, sorry. The dataset is too large, and I have no other appropriate ways to share it.

**Comment by Saddam1235** [comment]
Would you like to share it on google driver... and reply it's link? Else can i use test.py to predict on new images?

**Comment by LiheYoung** [comment]
I attempted google drive several times, but the speed was too slow, and the uploading process was frequently interrupted. Sorry.

The ``test.py`` is used for prediction.

**Comment by Saddam1235** [comment]
Thank you sir, for your response. now i am trying to use your predict.py. But i am getting error it is because i do not know whether it will take all types of satellite images or any specific type.i am giving two random satellite images in folder val, but it cant read. will you give me some hint please.

**Comment by LiheYoung** [comment]
Could you provide a screenshot of the "can't read error"?

**Comment by Saddam1235** [comment]
i am giving it two images of same scene taken at different time. it's 4 band imagery with 1.5 m resolution. i am getting this error:
RuntimeError: The size of tensor a (720) must match the size of tensor b (3) at non-singleton dimension 0
now i am using your models for prediction from test.py file.

**Comment by Saddam1235** [comment]
one more thing i am testing on device withour GPU. but have CPU with 128 GB.

**Comment by LiheYoung** [comment]
The code should be tested on GPU. And the input image should be of RGB mode (3 channels). 

Moreover, considering the domain gap among different satellite datasets, the provided model cannot be directly leveraged. It is better to re-train a model on your own dataset.

**Comment by Saddam1235** [comment]
could you please attach only one satellite image sample along with its label so that i can see the complete format for my datasets.

**Comment by Saddam1235** [comment]
Hi Sir,
Thanks for your guidance
i am struck at one place.. getting error in test.py. this is the error:
NameError: name 'iter_end_time' is not defined

kindly help, also time limit is not necessary in my case
