### ISSUE TITLE
模型的最终效果

### ISSUE THREAD

**Issue by Chuan-shanjia** [LiheYoung/SenseEarth2020-ChangeDetection#17]
您好！我正在复现您的代码，并打算应用于其他变化检测数据集。请问您在这个数据集中最后达到了什么样的精度呢？不同模型下的得分达到多少是合理的呢？
谢谢！

**Comment by LiheYoung** [comment]
大约是38～39左右

**Comment by Chuan-shanjia** [comment]
请问是hrnet_w18还是hrnet_w40呢？它们的得分相差多吗？谢谢！

**Comment by LiheYoung** [comment]
hrnet_w18是38.74，hrnet_w40是39.37
