### ISSUE TITLE
您好，我想向您请教一下数据集的问题

### ISSUE THREAD

**Issue by L-xiaolu** [LiheYoung/SenseEarth2020-ChangeDetection#18]
在该项目中的变化检测数据集中，我注意到有一个label1文件夹，我想请问该文件的作用是什么？谢谢，打扰到您的话，万分抱歉。

**Comment by LiheYoung** [comment]
您好，label1是表示图像1的语义分割的标签，其中白色的区域表示未变化区域，其他颜色的区域表示各种实际的语义类别。

可以参考比赛官网: https://rs.sensetime.com/competition/index.html#/data
