### ISSUE TITLE
关于模型的得分

### ISSUE THREAD

**Issue by J-rong** [LiheYoung/SenseEarth2020-ChangeDetection#19]
你好，我训练的hrnet_w18的得分最多只有36.65，没有办法达到38，是不是得引入伪标签才能提高分数呢？

**Comment by LiheYoung** [comment]
你好，是的，如果不利用伪标签，我们这边的HRNet-40大概是37.7左右，需要引入伪标签后才能提升到38+。

**Comment by J-rong** [comment]
好的，谢谢
