### ISSUE TITLE
输入尺寸多少

### ISSUE THREAD

**Issue by liufangtao** [LiheYoung/SenseEarth2020-ChangeDetection#20]
训练输入尺寸在哪设置，默认尺寸多大

**Comment by LiheYoung** [comment]
比赛中图是相同尺寸的，所以没有设置

**Comment by liufangtao** [comment]
我全部是1024像素的图片 能不能正常训练拉起？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/SenseEarth2020-ChangeDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/SenseEarth2020-ChangeDetection] 输入尺寸多少 (Issue #20)





 
比赛中图是相同尺寸的，所以没有设置

**Comment by LiheYoung** [comment]
可以尝试一下

**Comment by liufangtao** [comment]
这个工程对应 有没有论文 想详细研究一下，谢谢！大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/SenseEarth2020-ChangeDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/SenseEarth2020-ChangeDetection] 输入尺寸多少 (Issue #20)





 
可以尝试一下

**Comment by LiheYoung** [comment]
这边有一个[technical report](https://github.com/LiheYoung/SenseEarth2020-ChangeDetection/blob/d75592bcff4151c0b7fc02a81b735aae2fff7522/docs/technical%20report.pdf).

**Comment by liufangtao** [comment]
谢谢！这个工程里面是有这个文档。工程有没有新版本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/SenseEarth2020-ChangeDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月11日(星期一) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/SenseEarth2020-ChangeDetection] 输入尺寸多少 (Issue #20)





 
这边有一个technical report.

**Comment by LiheYoung** [comment]
不好意思，我们只有这个版本。
