### ISSUE TITLE
如果两张图会有小范围的平移和旋转还能用吗

### ISSUE THREAD

**Issue by nistarlwc** [LiheYoung/SenseEarth2020-ChangeDetection#3]
非当前的遥感应用，只是想用作图像对比，，但是输入图肯定会和参考图有一定平移和旋转，旋转应该不超过2°，像素不超过20pixel。。可以用吗

**Comment by LiheYoung** [comment]
应该可以得到大概的结果，但在变化的边缘处会不准确。

**Comment by nistarlwc** [comment]
> 应该可以得到大概的结果，但在变化的边缘处会不准确。

还没有细看网络结构，在合并两个HRNet特征的时候，是怎么做的呢？
直接堆叠、相加、还是相乘。感觉后两者的话，应该对平移旋转支持较差。
