### ISSUE TITLE
question

### ISSUE THREAD

**Issue by yak198914** [LiheYoung/SenseEarth2020-ChangeDetection#8]
你好，非常好的代码。我有几个疑问，test.py里out2的mask输出文件夹应该是im2吧。还有代码里有用特征向量和spphead求二值图了吗，非常想学习一下

**Comment by LiheYoung** [comment]
你好，谢谢关注。

“out2的mask输出文件夹应该是im2”，是的，谢谢指出。

求二值图用的是模型中的head_bin模块，因为PSPNet和FCN都是继承了base.py中的BaseNet，是在BaseNet中利用head_bin完成了二值图的计算：
```
out_bin = torch.abs(x1 - x2)
out_bin = self.head_bin(out_bin)
```

**Comment by yak198914** [comment]
你好，我还有疑问想向您请教。关于二值图的输出是保存在了out_bin那个列表里了吗，如果我想输出并保存二值图在test里如何实现呀，改了一下午代码结果都得到黑色的图像。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiheYoung/SenseEarth2020-ChangeDetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月1日(星期四) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LiheYoung/SenseEarth2020-ChangeDetection] question (#8)





 
你好，谢谢关注。
 
“out2的mask输出文件夹应该是im2”，是的，谢谢指出。
 
求二值图用的是模型中的head_bin模块，因为PSPNet和FCN都是继承了base.py中的BaseNet，是在BaseNet中利用head_bin完成了二值图的计算：
 out_bin = torch.abs(x1 - x2) out_bin = self.head_bin(out_bin)

**Comment by LiheYoung** [comment]
test.py中已经对所有模型得到的二值图进行ensemble得到了最终的out_bin:
```
out_bin = torch.stack(out_bin_list, dim=0)
out_bin = torch.sum(out_bin, dim=0) / len(models)
out_bin = (out_bin > 0.5)
```
但是此处out_bin中的值是0-1的，所以可视化的时候值为1的区域很难看得出，可以将1的区域设置为255再进行可视化:
```
out_bin *= 255
for i in range(out_bin.shape[0]):
    mask_bin = Image.fromarray(out_bin[i].astype(np.uint8))
    mask_bin.save("Path-to-store-binary-mask/" + id[i])
```

**Comment by LiheYoung** [comment]
如果有其他的问题请再打开这个issue，谢谢。

**Comment by yak198914** [comment]
你好，昨天晚上我调试了一下代码，test.py里out_bin为0的时候应该是认为变化的区域，
所以我觉得二值化结果如果默认白色区域为变化的区域的话应该是255-out_bin.astype(np.unit8)*255。


还有一个疑问就是对于两张图像，经过主干网输出两张图像对应的mask掩膜图像后，我运行程序得到的二值图是两张mask图像的并集，
举个例子就是两张图对应的一点都是土地，输出的二值图结果对应的点是变化的，多时相都是土地，对应的结果不应该是不变化的吗。
这里面的疑问如果可以烦请大佬为我解惑0.0，附上我跑的结果图。


im1,im2为预测的mask图，im3为head预测的二值图，im4是我自己写的求im1，im2差的二值图。

**Comment by LiheYoung** [comment]
你好，

如果认为白色代表变化区域，确实需要先对out_bin进行0、1的反转，因为代码中out_bin为0代表变化。

第二个问题确实是存在的，即out_bin对于变化与否的预测结果和out_1、out_2的预测结果可能不一致，我们在代码中选择了以out_bin为准，也就是下面这两行代码。当然，也完全可以根据out_1、out_2的预测结果经过处理后得到out_bin。
```
out1[out_bin == 1] = 0
out2[out_bin == 1] = 0
```
